solver:
    sdf_scale: 0.9
    resolution: 256
    save_sdf: False

model:
    name: graph_vae

    channel: 8
    depth: &depth 8
    nout: 4
    depth_out: *depth
    full_depth: &full_depth 4
    depth_stop: 6
    bottleneck: 4
    resblock_type: basic
    code_channel: 16
    resblk_num: 2

    embed_dim: 4
    n_embed: 8192
    use_checkpoint: True

data:
    train:
        name: shapenet

        # octree building
        depth: *depth
        offset: 0.0
        full_depth: *full_depth
        node_dis: True
        split_label: True

        # no data augmentation
        disable: False
        distort: False

        # data loading
        location: &location /mnt/gemlab_data_2/User_database/liangzhichao/octfusion_dataset_6/dataset
        filelist: &filelist /mnt/gemlab_data_2/User_database/liangzhichao/octfusion_dataset_6/filelist
        load_octree: &load_octree False
        load_pointcloud: &load_pointcloud True
        load_curve: &load_curve True
        load_split_small: &load_split_small False
        load_split_large: &load_split_large False
        load_sdf: &load_sdf False
        load_occu: &load_occu False
        load_color: &load_color False
        load_mask: &load_mask True
        load_graph: &load_graph True
        batch_size: &batch_size 8
        shuffle: True

        point_scale: &point_scale 0.5
        point_sample_num: 5000
        sample_surf_points: False
        in_memory: False
        num_workers: 4
        data_augmentation: true


    test:
        name: shapenet

        # octree building
        depth: *depth
        offset: 0.0
        full_depth: *full_depth
        node_dis: True
        split_label: True

        # no data augmentation
        disable: False
        distort: False

        # data loading
        location: *location
        filelist: *filelist
        batch_size: 1
        load_octree: *load_octree
        load_pointcloud: *load_pointcloud
        load_curve: *load_curve
        load_split_small: *load_split_small
        load_split_large: *load_split_large
        load_sdf: *load_sdf
        load_occu: *load_occu
        load_color: *load_color
        load_mask: *load_mask
        load_graph: *load_graph
        shuffle: False

        point_scale: *point_scale
        point_sample_num: 5000
        sample_surf_points: False
        in_memory: False
        num_workers: 8
